### ISSUE TITLE
Implement new hero section

### ISSUE THREAD

**Issue by siamkreative** [SiamKreative/tanja-keller.com#20]
### Todo
- [x] Add background slider instead of static image
- [x] Fading effect similar to this http://tanja-keller.com/
### Issues
- How to have a good looking image on mobile? If slider supports `background-position`, then need to change the `background-position` individually of each slides.

Example:

``` css
.hero {
    background-position: 23% 50%;
}
@media only screen and (min-width : 1200px) {
    .hero {
        background-position: 50% 100%;
    }
}
```
