### ISSUE TITLE
Fix Page Loader

### ISSUE THREAD

**Issue by siamkreative** [SiamKreative/tanja-keller.com#9]
Because I moved jQuery in the footer (in f8e3542), the script below doesn't execute right away:

``` javascript
function resizeNow() {
    var browserwidth = $(window).width();
    var browserheight = $(window).height();
    $('.pageloader-content').css('right', ((browserwidth - $(".pageloader-content").width()) / 2)).css('top', ((browserheight - $(".pageloader-content").height()) / 2));
}

resizeNow();
$(window).resize(resizeNow);
```

Let's use CSS instead for positioning this loader.

**Comment by SiamKreative** [comment]
Converting this into vanilla JS would allow to load before jQuery.

**Comment by siamkreative** [comment]
It's as simple as this...

``` css
.pageloader-content {
    top: 50%;
    right: 50%;
    margin-top: -50px;
    margin-right: -50px;
}
```
